### ISSUE TITLE
Received response: "Failed" (Error code 12)

### ISSUE THREAD

**Issue by ptr727** [loopj/aiovantage#7]
Using main source from v0.2.2.  
Running `dump_system.py`:

```
2023-06-20 10:41:53,762 [MainThread  ] [DEBUG] Sending command: INVOKE 870 Task.GetState
2023-06-20 10:41:53,773 [MainThread  ] [DEBUG] Received response: CommandResponse(command='INVOKE', args=['870', '1', 'Task.GetState'], data=[])
2023-06-20 10:41:53,775 [MainThread  ] [DEBUG] Sending command: ELLOG STATUS ON
2023-06-20 10:41:53,781 [MainThread  ] [INFO ] TasksController fetched full state
2023-06-20 10:41:53,791 [MainThread  ] [DEBUG] Received response: "Failed" (Error code 12)
2023-06-20 10:41:53,792 [MainThread  ] [DEBUG] Sending command: ELENABLE STATUSEX ON
2023-06-20 10:41:53,808 [MainThread  ] [DEBUG] <asyncio.sslproto.SSLProtocol object at 0x0000025BB0531E50>: Fatal error on transport
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\Lib\asyncio\sslproto.py", line 644, in _do_shutdown
    self._sslobj.unwrap()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\Lib\ssl.py", line 983, in unwrap
    return self._sslobj.shutdown()
           ^^^^^^^^^^^^^^^^^^^^^^^
ssl.SSLError: [SSL: APPLICATION_DATA_AFTER_CLOSE_NOTIFY] application data after close notify (_ssl.c:2702)
2023-06-20 10:41:53,813 [MainThread  ] [DEBUG] <_ProactorSocketTransport fd=1028> received EOF
2023-06-20 10:41:53,814 [MainThread  ] [DEBUG] <asyncio.sslproto.SSLProtocol object at 0x0000025BAEF37990> received EOF
2023-06-20 10:41:53,827 [MainThread  ] [DEBUG] Close <ProactorEventLoop running=False closed=False debug=True>
```

Exception emitted by `connection.py`:

```
        # Re-raise all other exceptions, including "R:ERROR" responses
        if isinstance(response, Exception):
            raise response
```

[aiovantage.log](https://github.com/loopj/aiovantage/files/11804629/aiovantage.log)

**Comment by loopj** [comment]
Thanks for the report @ptr727, taking a look at this now.

I'm wondering if your system doesn't like the calls to `ELENABLE` or `ELLOG` for some reason. Could you try to run the following and let me know what the output is:

```
import asyncio
from aiovantage.command_client import CommandClient

async def main():
    async with CommandClient("your_host", "username", "password") as client:
        print("System version: ")
        print(await client.command("VERSION"))

        print("ELLOG STATUS: ")
        print(await client.command("ELLOG STATUS ON"))
        print(await client.command("ELENABLE STATUS ON"))

        print("ELLOG STATUSEX: ")
        print(await client.command("ELLOG STATUSEX ON"))
        print(await client.command("ELENABLE STATUSEX ON"))

asyncio.run(main())
```

Hey you are getting actual data back from the Vantage system at least! :)

**Comment by loopj** [comment]
I think I've figured out why this is happening, pushing a potential fix.

**Comment by loopj** [comment]
Could you pull aiovantage 0.2.3 and tell me if this fixes the issue for you? Thanks in advance!

**Comment by ptr727** [comment]
You PR #8 fixes it.

**Comment by loopj** [comment]
FYI: I've cut https://github.com/loopj/hass-vantage/releases/tag/0.3.3 which includes aiovantage 0.2.3
